#!/bin/sh
set -e
echo "Running eslint:"
ESLINT_USE_FLAT_CONFIG=false npx eslint .
echo "Running prettier:"
npx prettier . --check
echo "Running Typescript unit tests:"
npm run ts-tests
echo "Checking TS types"
npx tsc