#!/bin/sh
set -e
echo "Running eslint:"
npx eslint --cache .
echo "Running prettier:"
npx prettier --cache . --check
echo "Running Typescript unit tests:"
npm run ts-tests
echo "Checking TS types"
npx tsc