// Also want "in", but only if it is after "With". Otherwise it's an English word.
// Also want "object" but only if preceding "- "
// Also want to connect "of thing;" with its preceding word

export const GRAMMAR_TERMS = new Set([
  "ut",
  "ad",
  "de",
  "ab",
  "ne",
  "cum",
  "object-clause",
  "ex",
  "quam",
  "object-",
  "se",
  "quod",
  "si",
  "double object",
  "subject-clause",
  "at",
  "quin",
  "aliquid",
  "atque",
  "contra",
  "aliquem",
  "inter se",
  "alicui",
  "adj",
  "an",
  "dum",
  "apud",
  "post",
  "absol",
  "sub",
  "etiam",
  "in aliquid",
  "bis;",
  "ubi",
  "nisi",
  "qui",
  "ita",
  "negative",
  "Subst",
  "alter",
  "que",
  "quia",
  "gentium",
  "usque",
  "Aliquid",
  "irregular",
  "ob",
  "super",
  "cur",
  "quo",
  "aut",
  "adjectives",
  "de aliquā re",
  "plur",
  "ad aliquid",
  "gerundive",
  "relative-clause",
  "adverbs",
  "subjectclause",
  "Aliquem",
  "in aliquā re",
  "Alicui",
  "circa",
  "figuratively",
  "how",
  "tam",
  "ab aliquo",
  "absolutely",
  "relative",
  "quando",
  "id",
  "alicui rei",
  "ipse",
  "vel",
  "adeo",
  "donec",
  "de aliqua re",
  "magis",
  "inf",
  "cum aliquo",
  "Alicui aliquid",
  "acc",
  "dat",
  "Comp",
  "Neutr",
  "Absol.",
  "Comp.",
  "Subst.",
  "subst.",
  "gen.",
  "Adv.",
  "inf.",
  "Sup.",
  "absol.",
  "acc.",
  "Plur.",
  "Act.",
  "dat.",
  "perf.",
  "Neutr.",
  "Pass.",
  "pass.",
  "Adj.",
  "sup.",
  "comp.",
  "P. a. fin.",
  "gen. plur.",
  "subj.",
  "adj. dim.",
  "Sing.",
  "part. perf.",
  "fem.",
  "act.",
  "neutr.",
  "Impers. pass.",
  "Impers.",
  "abl. sing.",
  "Pass. impers.",
  "masc.",
  "rel.-clause",
  "Fem.",
  "part.",
  "plur. subst.",
  "advv.",
  "adj. f.",
  "ext.",
  "in lemm.",
  "dep.",
  "P. a.",
  "Substt.",
  "fut.",
  "indic.",
  "Masc.",
  "impers.",
  "conj.",
  "adjj.",
  "gen. sing.",
  "Abl.",
  "obj.-clause",
  "substt.",
  "Plur. subst.",
  "Gen.",
  "abl. plur.",
  "part. pres.",
  "imperf.",
  "gen. obj.",
  "verb. finit.",
  "pres.",
  "inf. pass.",
  "nom. sing.",
  "perf. subj.",
  "Part. perf.",
  "abl. absol.",
  "imper.",
  "part. pass.",
  "acc. pers.",
  "subj.-clause",
  "dat. plur.",
  "pron.",
  "Dat.",
  "neutr. plur.",
  "acc. plur.",
  "Prep.",
  "rel.",
  "rel. clause",
  "acc.;",
  "pluperf.",
  "fut. perf.",
  "neutr. absol.",
  "prepp.",
  "absol.;",
  "Gen. plur.",
  "nom. plur.",
  "acc. sing.",
  "inf.-clause",
  "imperf. subj.",
  "dat. pers.",
  "perf. indic.",
  "Neutr. absol.",
  "intens.",
  "imp.",
  "imperf. indic.",
  "inf. pres.",
  "P. a.;",
  "pluperf. subj.",
  "gen. subj.",
  "P.a.",
  "part. fut.",
  "posit.",
  "Advv.",
  "gerund.",
  "pres. subj.",
  "adj. m.",
  "nom. propr.",
  "num. distr. adj.",
  "interrog.-clause",
  "neutr. pron.",
  "acc. rei",
  "in with acc.",
  "inf. pres. pass.",
  "Rel.",
  "Voc.",
  "Subst. plur.",
  "inf. perf.",
  "num. adv.",
  "perf. sync.",
  "adv. of place",
  "patr.",
  "rel.clause",
  "a proper name.",
  "Interrog.",
  "Neut.",
  "part. perf. pass.",
  "obj. gen.",
  "P a.",
  "dat. sing.",
  "pass. impers.",
  "nom. prop.",
  "tempp. perff.",
  "part. fut. pass.",
  "neutr. sing.",
  "nom.",
  "num. distrib. adj.",
  "Indef.",
  "pron. indef.",
  "Nom.",
  "accs.",
  "Neutr. plur.",
  "Posit.",
  "neg.",
  "neutr. subst.",
  "part. perf.;",
  "pers. pron.",
  "dat. of pers.",
  "Part. pass.",
  "acc. of person",
  "subst. plur.",
  "Subj.",
  "pass. signif.",
  "num. ord. adj.",
  "local adv.",
  "ut.",
  "imperat.",
  "patr. m.",
  "comp. abl.",
  "pres. inf.",
  "perf. inf.",
  "adj. prop.",
  "Dep.",
  "subj.;",
  "histor. pres.",
  "praes.",
  "card. num.",
  "Sing. collect.",
  "gen. part.",
  "dat.;",
  "Gr. acc.",
  "gen.;",
  "pres. indic.",
  "perf. part.",
  "compp.",
  "obj.",
  "d pers.",
  "dat. of person",
  "inf.;",
  "Abl. absol.",
  "interrog. clause",
  "Perf.",
  "Part. pres.",
  "praep.",
  "two acc.",
  "obj.clause",
  "plur. verb",
  "in with abl.",
  "pers.",
  "amplif.",
  "N. cr",
  "freq.",
  "v. desid. n.",
  "adv. dim.",
  "acc. of the person",
  "verb. fin.",
  "gen. plur. part.",
  "accus.",
  "ad.",
  "rel. pron.",
  "relat. clause",
  "sync.",
  "ne.",
  "plur. nom.",
  "adv. comp.",
  "acc. of thing;",
  "acc. of thing",
  "adj. comp.",
  "bis.",
  "pronn.",
  "gen. gerund.",
  "lemm.",
  "obj. acc.",
  "Acc. plur.",
  "temp. perf.",
  "v. pass.",
  "mid.",
  "impers. pass.",
  "pron. rel.",
  "ordin. num.",
  "not only ... but also",
  "neut.",
  "pron. demonstr.",
  "fut. part.",
  "gen. plur",
  "pron. poss.",
  "verb finit.",
  "subj. clause",
  "adv. temp.",
  "partit. gen.",
  "acc. fem.",
  "adj. comm.",
  "num.",
  "subj. imperf.",
  "Nom. plur.",
  "acc. and inf.",
  "f dim.",
  "reflex.",
  "sup.;",
  "v. desid. a.",
  "sing. acc.",
  "reflex. pron.",
  "plur. absol.",
  "neutr. acc.",
  "adj. fem.",
  "rel. -clause",
  "inf. act.",
  "double acc.",
  "dat. of the person",
  "part. praes.",
  "inf. clause",
  "neutr. plur. subst.",
  "V. a.",
  "demonstr.",
  "part. gen. plur.",
  "Conj.",
  "de.",
  "simple abl.",
  "extr.;",
  "patr. f.",
  "extr.",
  "part. fut. act.",
  "Imper.",
  "abl. fem.",
  "interrog.",
  "dat. f.",
  "doub. dim.",
  "subj. perf.",
  "subj. pres.",
  "pass.;",
  "Se.",
  "indef.",
  "acc. of the thing",
  "perf. redupl.",
  "inf. fut.",
  "Verb finit.",
  "v. dim. a.",
  "locat.",
  "num. distrib.",
  "st pers.",
  "cum.",
  "d pers. sing.",
  "inf.-clause.",
  "subst.;",
  "v a.",
  "obj.-gen.",
  "gen. rei",
  "P. a",
  "subj. inf.",
  "gen. object.",
  "pron. interrog.",
  "Imperf. subj.",
  "Indic.",
  "indic.;",
  "fut. indic.",
  "Pluperf.",
  "Imperf.",
  "acc. respect.",
  "simple subj.",
  "praepp.",
  "subj. gen.",
  "arch. inf. pass.",
  "fin., no.",
  "fut. inf.",
  "inf. praes. pass.",
  "distr. num.",
  "inf. praes.",
  "gen. plur. part. sync.",
  "gen. pretii",
  "perf. pass.",
  "voc.",
  "Neutr. subst.",
  "sing. collect.",
  "Fut.",
  "winged.",
  "adv. of place;",
  "adverb. acc.",
  "num. adj. indecl.",
  "st pers. plur.",
  "comp. clause",
  "d pers. plur.",
  "perf. pass. inf.",
  "temp. adv.",
  "v. a",
  "subst. m.",
  "in.",
  "interrog. pron.",
  "adv. interrog.",
  "Part. fut. pass.",
  "abl. pretii",
  "acc. of place",
  "fem. sing.",
  "indef. pronn.",
  "acc. of pers.",
  "fem.;",
  "free.",
  "super with acc.",
  "verb act.",
  "gen. of thing",
  "P. a. subst.",
  "dum.",
  "part. pres. gen. plur.",
  "v. n",
  "partt.",
  "subject inf.",
  "Dat. plur.",
  "impers.;",
  "v. n. desid.",
  "v. freq. act.",
  "N cr.",
  "acc. m.",
  "inf.clause",
  "pres. pass.",
  "predic. inf.",
  "Nom. propr.",
  "nom. sing. masc.",
  "N. cr.; abl.",
  "comp.;",
  "advv.;",
  "tempp. press.",
  "Intr.",
  "gen. pers.",
  "dat. of thing",
  "v. defect.",
  "adj. propr.",
  "perf. part. pass.",
  "v. dep.;",
  "tempp. perf.",
  "Verb. finit.",
  "pron. pers.",
  "acc., acc.",
  "Comp., sup.",
  "Part. and P. a.",
  "Pres.",
  "histor. inf.",
  "pres. perf.",
  "pluperf. indic.",
  "gen. pl.",
  "gen. partit.",
  "gen. of the thing",
  "infin. pass. parag.",
  "verb. finit.;",
  "praes. subj.",
  "inf. perf. sync.",
  "adv., with difficulty;",
  "abl. manner",
  "first pers.",
  "dim. adj.",
  "adv. demonstr.",
  "abstr.",
  "fut. part. act.",
  "object-clause.",
  "adj. indecl.",
  "Neutr. adv.",
  "subject.-clause",
  "Pass. part.",
  "indef. subj.",
  "abl. of manner",
  "Plur. absol.",
  "gen. of person",
  "adj. sup.",
  "intr.",
  "acc. of the pers.",
  "object.-gen.",
  "abl. adv.",
  "ne ... quidem",
  "neutr. adj.",
  "gen. fem.",
  "adj. ord.",
  "dat. m.",
  "acc. of neutr. pron.",
  "indic. pres.",
  "advv. of place",
  "Plur subst.",
  "dat. of agent",
  "adv. of time",
  "Neutr. adverb.",
  "nom. masc.",
  "masc. pron.",
  "adverb.-clause",
  "pass. inf. impers.",
  "pron. interrog",
  "infin.",
  "dim. f.",
  "subst. n.",
  "v. neutr.",
  "patron. f.",
  "patron.",
  "subject. gen.",
  "object. gen.",
  "pluperf.;",
  "part. pass.;",
  "adv. quo",
  "dim.",
  "abl. of means",
  "bis.;",
  "ab.",
  "cop. conj.",
  "verb. dep.",
  "absol. P. a.",
  "v. act.",
  "loc. adv.",
  "cum ... tum",
  "subst. pron.",
  "Abl. sing.",
  "acc. plur. neutr.",
  "comp. neutr.",
  "the one ... the other",
  "obliq. cas.",
  "abl. comp.",
  "masc.;",
  "dat. of person;",
  "subj. pluperf.",
  "fut. pass.",
  "dim. n.",
  "Pass. absol.",
  "Act. absol.",
  "in with abl.;",
  "Abl. plur.",
  "pos.",
  "perf subj.",
  "dim.;",
  "num. distr.",
  "dat. gerund",
  "dep. a.",
  "acc. sing. n.",
  "Plur. fem.",
  "piur.",
  "gen. of pers.",
  "subj.clause",
  "pass. inf.",
  "acc. respect",
  "acc. respectiv.",
  "temp. pres.",
  "fin..",
  "pred. nom.",
  "Tempp. press.",
  "partic.",
  "Phr.",
  "adj. gen. omn.",
  "Plur. neutr.",
  "acc., dat.",
  "indef. pron.",
  "plur.",
  "quin.",
  "Adjj.",
  "acc. plur.;",
  "Pres. subj.",
  "fut. imper.",
  "fem. gen.",
  "Sing. nom.",
  "Plur. nom.",
  "voc.;",
  "part. perf. absol.",
  "subjunct.",
  "acc. et inf.",
  "Part. gen. plur. sync.",
  "verb. act.",
  "v. int. a.",
  "abl. temp.",
  "abl. rei",
  "sync. perf.",
  "act. collat.",
  "obj. clause",
  "Perf. sync.",
  "supin.",
  "rel. adv.",
  "term. ad quem",
  "verb. fin. act.",
  "futur.",
  "subject acc.",
  "praes. histor.",
  "acc. masc.",
  "pers. plur.",
  "depon.",
  "Praep.",
  "simple acc.",
  "praes. indic.",
  "Reflex.",
  "abl. neutr. absol.",
  "abl. pers.",
  "med.—Comp.",
  "neutr. plur. absol.",
  "ellips.",
  "sing. nom.",
  "pron. possess.",
  "acc. of respect",
  "Dim.",
  "relat.-clause",
  "adv. loci",
  "dat. sing. fem.",
  "dat. rei",
  "init.—Sup.",
  "abl. specif.",
  "comp. adv.",
  "abl. instrum.",
  "V. n.",
  "acc. of the charge",
  "init.—Absol.",
  "Adj. comp.",
  "pass. part.",
  "se.",
  "neutr, sing.",
  "Neutr. sing.",
  "act.;",
  "subject.",
  "subst.-clause",
  "although ... yet",
  "v. a.; pass.",
  "neutr. of the demonstr.",
  "third pers. sing.",
  "gen. of place",
  "neutr. indecl.",
  "comp. adj.",
  "part. perf. subst.",
  "Pass. reflex.",
  "Neutr. plur",
  "gen. poss.",
  "gen. m.",
  "ord. num. adj.",
  "card. num. adj.",
  "num. card. adj.",
  "fin.; abl.",
  "acc. of the pers. and of the thing",
  "Partt.",
  "subst. indecl.",
  "abl. of measure",
  "interrog.clause",
  "abl. sing.;",
  "adj. pron.",
  "subj. -clause",
  "abl. of time",
  "plur. masc.",
  "acc. resp.",
  "adv. of direction",
  "acc. of distance",
  "Subst..",
  "Adj. prop.",
  "pron. reflex.",
  "perf.;",
  "comp.-clause",
  "Neutr. plur. absol.",
  "si.",
  "indef. obj.",
  "dat. gerund.",
  "plur. n.",
  "v. irreg. a.",
  "subj.-acc.",
  "attribut. gen.",
  "subject-nom.",
  "subjectnom.",
  "subject-acc.",
  "subject-inf.",
  "predic. noun",
  "correl.-clause",
  "imv.",
  "prepp. adv.",
  "adj. num.",
  "p. a.",
  "ind.",
]);
