// const x: [string, string][] = [
//   ["Calv. Inst.", "Calvin Institutio Chr. Religionis."],
//   ["card.", "cardinal."],
//   ["cf.", "confer (compare)[**.]"],
//   ["class.", "classic(al)."],
//   ["col.", "column."],
//   ["collat.", "collateral."],
//   ["collect.", "collective, -ly."],
//   ["com.", "comic, or in comedy."],
//   ["comm. or c.", "common gender."],
//   ["comp.", "comparative, or compound."],
//   ["compd.", "compound."],
//   ["conj.", "conjunction, or conjugation."],
//   ["constr.", "construed, construction."],
//   ["contr.", "contracted."],
//   ["Corp. Conf.", "Corpus Confessionum."],
//   ["correl.", "correlative, -ively."],
//   ["corresp.", "corresponding."],
//   ["Cuv.", "Cuvier."],
//   ["dat.", "dative."],
//   ["Ducang. or DuC.", "the Lexicon of Ducange."],
//   ["decl.", "declension."],
//   ["defect.", "defective."],
//   ["demonstr.", "demonstrative."],
//   ["dep.", "deponent. or dependent."],
//   ["depend.", "dependent."],
//   ["deriv.", "derived, -ative, -ation."],
//   ["Dict. Ant.", "Dictionary of Greek and Roman Antiquities."],
//   ["diff.", "different."],
//   ["dim.", "diminutive."],
//   ["disyl.", "disyllable, -abic."],
//   ,
//   ["distr.", "distributive."],
//   ["Död. or Döderl.", "Döderlein's Synonyms."],
//   ["dub.", "doubtful."],
//   ["eccl.", "ecclesiastical."],
//   ["ed.", "editio."],
//   ["e. g.", "for example."],
//   ["ellipt.", "elliptical, -ly."],
//   ["Eng.", "English."],
//   ["Epith.", "Epithet."],
//   ["equiv.", "equivalent."],
//   ["Erasm. Coll.", "Erasmi Colloquia. (Ed. Tauch.)"],
//   ["esp.", "especially."],
//   ["etym.", "etymology, -gical."],
//   ["euphon.", "euphonic, -ny."],
//   ["ex.", "example."],
//   ["exx.", "examples."],
//   ["expr.", "express, expressed."],
//   ["extr.", "quite at the end."],
//   ["Fabr.", "Fabricius."],
//   ["fem.", "feminine."],
//   ["fig.", "figure, -ative, -atively."],
//   ["fin.", "at or towards the end."],
//   ["ad fin.", "at or towards the end."],
//   ["finit.", "finite (opposed to infinitive)."],
//   ["foll.", "following."],
//   ["fr.", "from. or fragmenta."],
//   ["Forcell.", "Forcellini."],
//   ["Forc.", "Forcellini."],
//   ["Fr.", "French."],
//   ["fragm.", "fragmenta."],
//   ["frag.", "fragmenta."],
//   ["freq.", "frequentative or frequent, -ly."],
//   ["fut.", "future."],
//   ["gen.", "genitive, generally, generic,--in gen., in a general sense."],
//   ["geog.", "geography, -ical."],
//   ["Georg.", " the Germ.-Lat. Lexicon of Georges."],
//   ["L. G.", " the Germ.-Lat. Lexicon of Georges."],
//   ["ger.", "gerund."],
//   ["Germ.", "German."],
//   ["gram.", " grammar, -ian, -atical."],
//   ["Gr.", "Greek."],
//   ["Hab.", "Habicht's Synonyms."],
//   ["hist.", "history, -ian."],
//   ["hypoth.", "hypothetical."],
//   ["i. e.", "id est."],
//   ["i. q.", "idem quod (the same as)"],
//   ["ib.", "ibidem. (in the same place)"],
//   ["id.", "idem. (the same)"],
//   ["imperat., imper., imperative."],
//   ["imperf.", "imperfect."],
//   ["impers.", "impersonal, -ly."],
//   ,
//   ["incep.", "inceptive."],
//   ["indecl.", "indeclinable."],
//   ["indef.", "indefinite."],
//   ["indic.", "indicative."],
//   ["inf.", "infinitive."],
//   ["init., in or ad init., at or near the beginning."],
//   ["inscrr.", "inscriptions."],
//   ["interj.", "interjection."],
//   ["interrog.", "interrogative, -tion."],
//   ,
//   ["intrans.", "intransitive."],
//   ["i. q.", "idem quod."],
//   ["irreg.", "irregular."],
//   ["ICtus", "juris consultus."],
//   ["jurid.", "juridical."],
//   ["Kr.", "Kraft's Germ.-Lat. Lexicon."],
//   ["lang.", "language."],
//   ["Lat.", "Latin."],
//   ["L. G.", "Student's Latin Grammar by Dr. Smith and Mr. Hall."],
//   ["l.", "lege or lectio."],
//   ["leg., legit, legunt, legal[** .]"],
//   ["L. or Linn.", "Linnaeus."],
//   ["lit., literal, in a literal sense."],
//   ["l. c. or loc. cit.", "loco citato."],
//   ["m. or masc.", "masculine."],
//   ["Madvig", "Madvig's Latin Grammar."],
//   ["math.", "mathematics, -ical."],
//   ,
//   ["Mayne", "Mayne's Expository Lexicon."],
//   ["Med. Lat.", "Mediaeval Latin."],
//   ["med., medio (in the middle); ad med., near the middle."],
//   ["medic.", "medical."],
//   ["met. or metaph.", "metaphorical, -ly."],
//   ,
//   ["meton.", "by metonymy."],
//   ["milit., military, in milltary[** military] affairs."],
//   ["M. L.", "Modern Latin."],
//   ["min.", "minor."],
//   ["Mosh.", "Mosheim."],
//   ["MS.", "manuscript."],
//   ["Mur. or Muret.", "Muretus."],
//   ["Nägels, or Näg., Stilistik of Nägelsbach."],
//   ["naut.", "nautical."],
//   ["n. or neut.", "neuter."],
//   ["neg.", "negative, -ly."],
//   ,
//   ["nom.", "nominative."],
//   ["num. or numer.", "numeral."],
//   ["O. E.", "Old English."],
//   ["obj. or object., objective.[** ,] -ly."],
//   ["obs.", "observe."],
//   ["opp., opposed to, opposite, -tion[** .]"],
//   ["ord.", "ordinal."],
//   ["orig., origin, original, originally."],
//   ["P., Putschius, Grammaticae Latinae Auctores, Hanov. 1605."],
//   ["p.", "page."],
//   ["part.", "participle."],
//   ["partit.", "partitive."],
//   ["pass., passive, -ly or passim."],
//   ["perf.", "perfect."],
//   ["perh.", "perhaps."],
//   ["pers.", "personal, -ly."],
//   ,
//   ["philos., philosophy, -ical, -ically, -opher."],
//   ["Phr., Phrase, Phrases."],
//   ["Phys.", "physical, -ly."],
//   ,
//   ["pleon.", "pleonastically."],
//   ["pl., plu. or plur., plural."],
//   ["poet., poeta, poetical, -ly."],
//   ["pos.", "positive."],
//   ["praef.", "praefatio."],
//   ["preced.", "preceding."],
//   ["prep.", "preposition."],
//   ["prob.", "probably."],
//   ["prol.", "prologus."],
//   ["pron., pronoun,"],
//   ["pronom.", "pronominal."],
//   ["prop., proper, -ly, in a proper sense."],
//   ["proverb.", "proverbial, -ly."],
//   ,
//   ["Quich. or Q.", "the French-Latin Lex. of Quicherat."],
//   ["qs.", "quasi."],
//   ["q. v., quod vide, videas."],
//   ["R and A.", "Riddle and Arnold."],
//   ["rad.", "radical or root."],
//   ["rar.", "rare, -ly."],
//   ,
//   ["ref.", "refer, -ence."],
//   ,
//   ["reflect.", "reflective, -tively."],
//   ,
//   ["rel.", "relative."],
//   ["rhet., rhetor., rhetoric, -al; in rhetoric."],
//   ["Rom.", "Roman."],
//   ["Ruhnk.", "Ruhnken."],
//   ["rt.[** .", "] root."],
//   ["sc.", "scilicet."],
//   ["Schleusn.", "Schleusner's New Test. Lex[** .]"],
//   ["Spreng.", "Sprengel."],
//   ["sq.", "sequens (and the following)[** .]"],
//   ["s.", "seu."],
//   ["s. v.", "sub voce."],
//   ["sign., signif., signifies, -cation."],
//   ["sing.", "singular."],
//   ["SS.", "Sanctae Scripturae."],
//   ["subaud.", "subauditur."],
//   ["subject. or subj.", "subjective, -ly."],
//   ,
//   ["subj.", "subjunctive."],
//   ["subst.", "substantive(ly)."],
//   ["suff.", "suffix."],
//   ["sup.", "superlative or supine."],
//   ["syl.", "syllable."],
//   ["syn.", "synonym."],
//   ["sync.", "syncopated."],
//   ["syncop.", "syncopated."],
//   ["t. t.", "technical term."],
//   ["term.", "termination."],
//   ["theol.", "theological."],
//   ["trans.", "transitive."],
//   ["transf.", "transferred."],
//   ["Tursell.", "Tursellinus."],
//   ["usu.", "usually."],
//   ["voc.", "vocative."],
//   ["Vulg.", "Vulgate."],
//   ["Wahl", "Wahl's New Test. Lexicon."],
//   ["Wytt. or Wyttenb.", "Wyttenbach."],
//   ["Zumpt", "Zumpt's Latin Grammar."],
// ];
