import { AuthorData } from "@/common/smith_and_hall/sh_abbreviations";

export const SH_AUTHORS_PROCESSED: AuthorData[] = [
  {
    abbreviations: ["Aem. Mac."],
    expansions: "Aemilius Macer, poet,",
    date: "obiit B.C. 16",
  },
  {
    abbreviations: ["Afran."],
    expansions: "Lucius Afranius, writer of comedy,",
    date: "flor. B.C. 94",
  },
  {
    abbreviations: ["Aggen."],
    expansions: "Aggenus Urbicus, writer on husbandry,",
    date: "circa A.D. 4th cent.",
  },
  {
    abbreviations: ["Albin."],
    expansions: "C. Pedo Albinovanus, poet,",
    date: "flor. A.D. 8",
  },
  {
    abbreviations: ["Alcim."],
    expansions: "Alcimus Avitus, Christian writer,",
    date: "flor. A.D. 360",
  },
  {
    abbreviations: ["Alfen."],
    expansions: "P. Alfenus Varus, lawyer,",
    date: "flor. B.C. 22",
  },
  {
    abbreviations: ["Amm."],
    expansions: "Ammianus Marcellinus, hist.,",
    date: "flor. A.D. 380",
  },
  {
    abbreviations: ["Ampel."],
    expansions: "L. Ampelius, hist.",
    date: "about A.D. 300",
  },
  {
    abbreviations: ["Apic."],
    expansions: "Apicius Coelius, writer on cookery (date of work unknown).",
  },
  {
    abbreviations: ["Apul.", "Appul.", "App."],
    expansions: "Lucius Apuleius, philosopher, (Ed. Delph.).",
    date: "about A.D. 150",
    works: [
      [["Apol."], "Apologia or De Magia."],
      [["Flor."], "Florida."],
      [["Met.", "M."], "Metamorphoses."],
      [["Trism."], "Trismegistus."],
    ],
  },
  {
    abbreviations: ["Apul.", "App."],
    expansions: "L. Apuleius Barbarus, botanical writer,",
    date: "about about A.D. 350",
    works: [[["Herb."], "Herbarium."]],
  },
  {
    abbreviations: ["Arn.", "Arnob."],
    expansions: "Arnobius Afer, Chr. writer,",
    date: "about A.D. 297",
  },
  {
    abbreviations: ["Ascon."],
    expansions: "Q. Asconius Pedianus, grammarian,",
    date: "about A.D. 40",
  },
  {
    abbreviations: ["Asin."],
    expansions: "C. Asinius Pollio, orator and hist.",
    date: "ob. A.D. 4",
  },
  {
    abbreviations: ["Att.", "Acc."],
    expansions: "L. Attius or Accius, writer of tragedy,",
    date: "fl. B.C. 130",
  },
  {
    abbreviations: ["Auct. B. Afr."],
    expansions: "Auctor Belli Africani.",
  },
  {
    abbreviations: ["Auct. B. Alex."],
    expansions: "Auctor Belli Alexandrini.",
  },
  {
    abbreviations: ["Auct. B. Hisp."],
    expansions: "Auctor Belli Hispaniensis.",
  },
  {
    abbreviations: ["Auct. Har. resp."],
    expansions:
      "Auctor de Haruspicum responsis (a speech usu. attributed to Cicero).",
  },
  {
    abbreviations: ["Auct. pro Dom."],
    expansions: "Auctor pro Domo sua (a speech usu. attributed to Cicero).",
  },
  {
    abbreviations: ["Auct. Her."],
    expansions: "Auctor ad Herennium, rhet.",
  },
  {
    abbreviations: ["Auct. Pervig. Ven."],
    expansions: "Auctor Pervigilii Veneris.",
  },
  {
    abbreviations: ["Aug."],
    expansions: "Aurelius Augustinus, Christian writer,",
    date: "ob. A.D. 430",
    works: [[["Civ. D."], "de Civitate Dei."]],
  },
  {
    abbreviations: ["August."],
    expansions: "Caesar Octavianus Augustus,",
    date: "ob. A.D. 14",
  },
  {
    abbreviations: ["Aur. Vict."],
    expansions: "Sextus Aurelius Victor, hist.",
    date: "fl. A.D. 358",
  },
  {
    abbreviations: ["Aus."],
    expansions: "D. Magnus Ausonius, poet,",
    date: "fl. A.D. 350",
    works: [
      [["Ecl."], "Eclogarium."],
      [["Ep."], "Epistolae."],
      [["Epigr."], "Epigrammata."],
      [["Epit."], "Epitaphia."],
      [["Grat. Act."], "Gratiarum Actio."],
      [["Idyll."], "Idyllia. or Edyllia."],
      [["Parent."], "Parentalia."],
      [["Per."], "Periochae."],
      [["Prof."], "Professores."],
      [["Sap."], "Sapientes."],
    ],
  },
  {
    abbreviations: ["Avien."],
    expansions: "R. Festus Avienus, poet,",
    date: "fl. A.D. 370",
  },
  {
    abbreviations: ["Boëth."],
    expansions: "Anicius Manl. Torq. Severinus Boëthius, phil.",
    date: "ob. A.D. 524",
  },
  {
    abbreviations: ["Brut."],
    expansions: "M. Junius Brutus,",
    date: "ob. B.C. 42",
  },
  {
    abbreviations: ["Caecil."],
    expansions: "Caecilius Statius, writer of comedy,",
    date: "ob. B.C. 168",
  },
  {
    abbreviations: ["Caes."],
    expansions: "Caius Julius Caesar, hist.",
    date: "ob. B.C. 44",
    works: [
      [["B. C."], "Bellum Civile."],
      [["B. G."], "Bellum Gallicum."],
    ],
  },
  {
    abbreviations: ["Callistr."],
    expansions: "Callistratus, lawyer,",
    date: "fl. A.D. 200",
  },
  {
    abbreviations: ["Calp."],
    expansions: "T. Julius Calpurnius, poet,",
    date: "perh. about fl. A.D. 285",
  },
  {
    abbreviations: ["Cap. or Mart. Cap."],
    expansions: "Martianus Mineus Felix Capella, encyclopaedist,",
    date: "about fl. A.D. 480",
  },
  {
    abbreviations: ["Capitol."],
    expansions: "Julius Capitolinus, biographer,",
    date: "about fl. A.D. 293",
  },
  {
    abbreviations: ["Cass. Hem."],
    expansions: "L. Cassius Hemina, hist.",
    date: "fl. B.C. 140",
  },
  {
    abbreviations: ["Cassiod."],
    expansions: "M. A. Cassiodorus, hist.",
    date: "ob. A.D. 562",
  },
  {
    abbreviations: ["Cato"],
    expansions: "M. Porcius Cato, orator and hist.",
    date: "ob. B.C. 149",
    works: [[["R. R."], "De Re rustica."]],
  },
  {
    abbreviations: ["Cat."],
    expansions: "C. Valerius Catullus, poet,",
    date: "fl. B.C. 55",
  },
  {
    abbreviations: ["Cels."],
    expansions: "A. Cornelius Celsus, physician,",
    date: "perh. fl. A.D. 25",
  },
  {
    abbreviations: ["Censor."],
    expansions: "Censorinus, chronologist,",
    date: "fl. A.D. 238",
  },
  {
    abbreviations: ["Charis."],
    expansions: "Flavius Sosipater Charisius, grammarian,",
    date: "fl. A.D. 400",
  },
  {
    abbreviations: ["Cic."],
    expansions: "M. Tullius Cicero, orator and philosopher,",
    date: "ob. B.C. 43",
    works: [
      [["Acad."], "Academicae Quaestiones."],
      [["Aem. Scaur."], "Oratio pro Aemilio Scauro (Frag.)."],
      [["Agr."], "Orationes de lege Agraria."],
      [["Am."], "de Amicitia. or Laelius."],
      [["Arat."], "transl. of Aratus."],
      [["Arch."], "Oratio pro Archia."],
      [["Att."], "Epistolae ad Atticum."],
      [["Balb."], "Oratio pro L. Corn. Balbo."],
      [["Brut."], "Brutus seu de Claris Oratoribus."],
      [["ad Br."], "Epistolae ad Brutum."],
      [["Caecin."], "Oratio pro Caecina."],
      [["Cat."], "Orationes in Catilinam."],
      [["Clod. et Cur."], "Oratio in Clodium et Curionem (Frag.)"],
      [["Cl.", "Clu."], "Oratio pro Cluentio."],
      [["Coel."], "Oratio pro M. Coelio."],
      [["Deiot."], "Oratio pro Rege Deiotaro."],
      [["Div."], "De Divinatione."],
      [["Div. in Caecil.", "Div. Verr."], "Divinatio in Caecilium."],
      [["Dom."], "Oratio pro Domo."],
      [["Fam."], "Epistolae ad Familiares."],
      [["Fat."], "De Fato."],
      [["Fin."], "de Finibus."],
      [["Flac.", "Fl."], "Oratio pro L. Flacco."],
      [["Font."], "Oratio pro M. Fonteio."],
      [["Fragm.", "Fr."], "Fragmenta."],
      [["Inv."], "De Inventione."],
      [["Leg."], "De Legibus."],
      [["Lig."], "Oratio pro Ligario."],
      [["Man.", "Manil."], "Oratio pro lege Manilia."],
      [["Marcell."], "Oratio pro Marcello."],
      [["Mil."], "Oratio pro Milone."],
      [["Mur."], "Oratio pro L. Murena."],
      [["N. D."], "De Natura Deorum."],
      [["Off."], "De Officiis."],
      [["Opt. Gen."], "De Optimo Genere Oratorum."],
      [["Or."], "Orator. ad M. Brutum."],
      [["de Or.", "De Or."], "De Oratore."],
      [["Par."], "Paradoxa."],
      [["Part. Or."], "Partitiones Oratoriae."],
      [["Phil."], "Orationes Philippicae."],
      [["Pis."], "Oratio in Pisonem."],
      [["Planc.", "Pl."], "Oratio Pro Plancio."],
      [["Prov. Cons."], "De Provinciis Consularibus."],
      [["Quint."], "Oratio pro P. Quintio."],
      [["Q. Fr."], "Epistolae ad Q. Fratrem."],
      [["Rab. Perd.", "C. Rab."], "Oratio Pro Rabirio perduellionis reo."],
      [["Rab. Post."], "Oratio pro Rabirio Postumo."],
      [["Rosc. Am.", "R. Am."], "Oratio pro Roscio Amerino."],
      [["Rosc. Com.", "R. Com."], "Oratio pro Roscio Comoedo."],
      [["Rep."], "De Republica."],
      [["De Sen.", "Sen."], "De Senectute or Cato Major."],
      [["Sest.", "Sext."], "Oratio pro Sestio (Sextio)."],
      [["Sull."], "Oratio pro Sulla."],
      [["Top."], "Topica."],
      [["Tull."], "Oratio pro. M. Tullio (Frag.)."],
      [["Tusc."], "Disputationes Tusculanae."],
      [["Tim."], "Timaeus or De Universo."],
      [["Vatin."], "Oratio in Vatinium."],
      [["Verr."], "Orationes in Verrem."],
      [["Div. Verr."], "Orationes in Verrem."],
      [["Verr. Act."], "Orationes in Verrem."],
    ],
  },
  {
    abbreviations: ["Claud."],
    expansions: "Claudius Claudianus, poet,",
    date: "fl. A.D. 395",
  },
  {
    abbreviations: ["Cod."],
    expansions: "Codex.",
    works: [
      [["Greg."], "Gregorianus."],
      [["Hermog."], "Hermogenianus."],
      [["Just."], "Justinianus."],
      [["Theod."], "Theodosianus."],
    ],
  },
  {
    abbreviations: ["Coel. Aurel."],
    expansions: "Coelius Aurelianus, physician,",
    date: "(date uncertain, but not later than 3rd cent. A.D.).",
    works: [
      [["Acut."], "Acutae Passiones."],
      [["Tard."], "Tardae Passiones."],
    ],
  },
  {
    abbreviations: ["Col."],
    expansions: "L. Jul. Moderatus Columella, writer on husbandry,",
    date: "fl. A.D. 20",
    works: [[["Arb."], "De Arboribus."]],
  },
  {
    abbreviations: ["Commod."],
    expansions: "Commodianus, Chr. poet,",
    date: "fl. A.D. 270",
  },
  {
    abbreviations: ["Coripp."],
    expansions: "Fl. Cresconius Corippus, poet and grammarian,",
    date: "fl. A.D. 566",
  },
  {
    abbreviations: ["Curt."],
    expansions:
      "Q. Curtius Rufus, hist. prob. 1st cent. A.D.; acc. to Buttmann,",
    date: "fl. A.D. 69",
  },
  {
    abbreviations: ["Cypr."],
    expansions: "Thascius Caecilius Cyprianus, Chr. writer,",
    date: "ob. A.D. 258",
  },
  {
    abbreviations: ["Dig."],
    expansions: "Digesta, i. e. libri Pandectarum",
  },
  {
    abbreviations: ["Diom."],
    expansions: "Diomedes, grammarian, prob. 5th cent. A.D.",
  },
  {
    abbreviations: ["Donat. or Don."],
    expansions: "Aelius Donatus, grammarian and commentator,",
    date: "fl. A.D. 350",
  },
  {
    abbreviations: ["Eccl."],
    expansions: "Scriptores Ecclesiastici.",
  },
  {
    abbreviations: ["Enn."],
    expansions: "Q. Ennius, poet,",
    date: "ob. B.C. 169",
  },
  {
    abbreviations: ["Eutr."],
    expansions: "Flavius Eutropius, hist.",
    date: "fl. A.D. 360",
  },
  {
    abbreviations: ["Fenest."],
    expansions: "L. Fenestella, hist.",
    date: "ob. A.D. 21",
  },
  {
    abbreviations: ["Fest."],
    expansions: "Sext. Pompeius Festus, grammarian,",
    date: "4th cent. A.D.",
  },
  {
    abbreviations: ["Firm."],
    expansions: "Julius Firmicus Maternus, mathematician,",
    date: "fl. A.D. 340",
  },
  {
    abbreviations: ["Flor."],
    expansions: "L. Annaeus Florus, hist.",
    date: "fl. A.D. 115",
  },
  {
    abbreviations: ["Fronto or Front."],
    expansions: "M. Cornelius Fronto, orator,",
    date: "fl. A.D. 150",
  },
  {
    abbreviations: ["Frontin. or Front."],
    expansions:
      "S. Julius Frontinus, writer De Strategematis, de Aquaeductibus, etc.",
    date: "ob. A.D. 106",
  },
  {
    abbreviations: ["Fulg."],
    expansions: "Fabius Planciades Fulgentius, grammarian,",
    date: "6th cent. A.D.",
  },
  {
    abbreviations: ["Gai. or Cai."],
    expansions: "Gaius or Caius, lawyer,",
    date: "fl. A.D. 160",
  },
  {
    abbreviations: ["Gall."],
    expansions: "C. Cornelius Gallus, poet,",
    date: "ob. B.C. 26",
  },
  {
    abbreviations: ["Gell."],
    expansions: "Aulus Gellius, gram., etc.",
    date: "fl. A.D. 150",
  },
  {
    abbreviations: ["Gloss."],
    expansions: "Glossarium.",
    works: [
      [["Cyril."], "Cyrilli."],
      [["Philox."], "Philoxem."],
    ],
  },
  {
    abbreviations: ["Grat. Falisc."],
    expansions: "Gratius Faliscus, poet,",
    date: "fl. B.C. 6",
  },
  {
    abbreviations: ["Hier."],
    expansions: "Hieronymus (Jerome), Chr. writer,",
    date: "ob. A.D. 420",
  },
  {
    abbreviations: ["Hirt."],
    expansions: "Aulus Hirtius, hist.",
    date: "ob. B.C. 43",
  },
  {
    abbreviations: ["Hor."],
    expansions: "Q. Horatius Flaccus, poet,",
    date: "ob. B.C. 8",
    works: [
      [["A. P."], "Ars Poetica."],
      [["Carm. Sec."], "Carmen Seculare."],
      [["Ep."], "Epistolae."],
      [["Epod."], "Epodi."],
      [["Od."], "Odae."],
      [["S."], "Satirae."],
    ],
  },
  {
    abbreviations: ["Hyg."],
    expansions: "C. Julius Hyginus, poet and fabulist,",
    date: "fl. A.D. 4",
    works: [
      [["Ast."], "Astronomia."],
      [["F."], "Fabellae."],
    ],
  },
  {
    abbreviations: ["Hyg."],
    expansions: "Hyginus Gromaticus, writer on surveying,",
    date: "fl. A.D. 110",
  },
  {
    abbreviations: ["Inscr."],
    expansions: "Inscriptiones.",
    works: [
      [["Don."], "Donii."],
      [["Fabr."], "Fabretti."],
      [["Graev."], "Graevii."],
      [["Grut."], "Gruteri."],
      [["Gud."], "Gudii."],
      [["Maff."], "Maffeii."],
      [["Murat."], "Muratorii."],
      [["Orell."], "Orelli."],
      [["Rein."], "Reinesii."],
    ],
  },
  {
    abbreviations: ["Isid."],
    expansions: "Isidorus Hispalensis, gram.",
    date: "ob. A.D. 636",
    works: [[["Orig."], "Origines."]],
  },
  {
    abbreviations: ["Jabol."],
    expansions: "Jabolenus or Javolenus Priscus, lawyer,",
    date: "fl. A.D. 120",
  },
  {
    abbreviations: ["Jornand."],
    expansions: "Jornandes, hist.",
    date: "about fl. A.D. 550",
  },
  {
    abbreviations: ["Julian."],
    expansions: "Salvius Julianus, lawyer,",
    date: "fl. A.D. 148",
  },
  {
    abbreviations: ["Just."],
    expansions: "Justinus, hist.",
    date: "(date unknown)",
  },
  {
    abbreviations: ["Justin. or Just."],
    expansions: "Justinianus, emperor,",
    date: "ob. A.D. 565",
  },
  {
    abbreviations: ["Juv."],
    expansions: "D. Junius Juvenalis, poet,",
    date: "fl. A.D. 82",
  },
  {
    abbreviations: ["Laber."],
    expansions: "C. Decius Laberius, mimographer,",
    date: "ob. A.D. 43",
  },
  {
    abbreviations: ["Lact."],
    expansions: "L. Coelius Lactantius Firmianus, Chr. writer,",
    date: "fl. A.D. 301",
  },
  {
    abbreviations: ["Lampr."],
    expansions: "Aelius Lampridius, hist.",
    date: "about fl. A.D. 293",
  },
  {
    abbreviations: ["Leg. XII. Tab."],
    expansions: "Leges duodecim tabularum,",
    date: "fl. B.C. 450",
  },
  {
    abbreviations: ["Liv."],
    expansions: "Titus Livius Patavinus, hist.",
    date: "ob. A.D. 17",
  },
  {
    abbreviations: ["Liv. Andron."],
    expansions: "Livius Andronicus, writer of tragedy,",
    date: "fl. B.C. 240",
  },
  {
    abbreviations: ["Lucan."],
    expansions: "M. Annaeus Lucanus, poet,",
    date: "ob. A.D. 65",
  },
  {
    abbreviations: ["Lucil."],
    expansions: "C. Ennius Lucilius, satirist,",
    date: "ob. B.C. 103",
  },
  {
    abbreviations: ["Lucr."],
    expansions: "T. Lucretius Carus, poet and philosopher,",
    date: "about ob. B.C. 50",
  },
  {
    abbreviations: ["M. Corvin."],
    expansions: "Messala Corvinus, hist.",
    date: "fl. B.C. 10",
  },
  {
    abbreviations: ["Macr."],
    expansions: "Aur. Theodosius Macrobius, critic,",
    date: "fl. A.D. 395",
    works: [
      [["Sat.", "S."], "Saturnalia."],
      [["Somn. Scip."], "Somnium Scipionis."],
    ],
  },
  {
    abbreviations: ["Mamert."],
    expansions: "Claudius Mamertinus, panegyrist,",
    date: "fl. A.D. 290",
  },
  {
    abbreviations: ["Manil."],
    expansions: "M. Manilius, poet,",
    date: "fl. A.D. 16",
  },
  {
    abbreviations: ["Marc."],
    expansions: "Aelius Marcianus, lawyer,",
    date: "fl. A.D. 230",
  },
  {
    abbreviations: ["Marc. Emp."],
    expansions: "Marcellus Empiricus, physician,",
    date: "fl. A.D. 400",
  },
  {
    abbreviations: ["Mart."],
    expansions: "M. Valerius Martialis, poet,",
    date: "ob. A.D. 104",
  },
  {
    abbreviations: ["Mela."],
    expansions: "Pomponius Mela, geographer,",
    date: "fl. A.D. 45",
  },
  {
    abbreviations: ["Min. Fel."],
    expansions: "Minutius Felix, Chr. writer,",
    date: "fl. A.D. 230",
  },
  {
    abbreviations: ["Modest."],
    expansions: "Herennius Modestinus, lawyer,",
    date: "fl. A.D. 230",
  },
  {
    abbreviations: ["Naev."],
    expansions: "C. Naevius, poet,",
    date: "ob. B.C. 202",
  },
  {
    abbreviations: ["Nemes."],
    expansions: "M. Aur. Olympius Nemesianus, poet,",
    date: "fl. A.D. 288",
  },
  {
    abbreviations: ["Nep."],
    expansions: "Cornelius Nepos, biographer,",
    date: "fl. B.C. 44",
    works: [
      [["Ages."], "Agesilaus."],
      [["Alcib."], "Alcibiades."],
      [["Arist."], "Aristides."],
      [["Att."], "Atticus."],
      [["Cat."], "M. Porcius Cato."],
      [["Chabr."], "Chabrias."],
      [["Cim."], "Cimon."],
      [["Con."], "Conon."],
      [["Dat."], "Datames."],
      [["Dion"], "Dion."],
      [["Epam."], "Epaminondas."],
      [["Eum."], "Eumenes."],
      [["Ham."], "Hamilcar."],
      [["Hann."], "Hannibal."],
      [["Iph."], "Iphicrates."],
      [["Lys."], "Lysander."],
      [["Milt."], "Miltiades."],
      [["Paus."], "Pausanias."],
      [["Pelop."], "Pelopidas."],
      [["Phoc."], "Phocion."],
      [["Reg."], "De Regibus."],
      [["Them."], "Themistocles."],
      [["Thras."], "Thrasybulus."],
      [["Tim.", "Timol."], "Timoleon."],
      [["Timoth."], "Timotheus."],
    ],
  },
  {
    abbreviations: ["Nigid."],
    expansions: "P. Nigidius Figulus, philos.",
    date: "fl. B.C. 64",
  },
  {
    abbreviations: ["Novat."],
    expansions: "Novatianus, Chr. writer,",
    date: "fl. A.D. 251",
  },
  {
    abbreviations: ["Non."],
    expansions: "Nonius Marcellus, gram.",
    date: "between 2nd and 5th cent. A.D.",
  },
  {
    abbreviations: ["Obseq."],
    expansions: "Julius Obsequens, writer De Prodigiis.",
  },
  {
    abbreviations: ["Ov."],
    expansions: "P. Ovidius Naso, poet,",
    date: "ob. A.D. 18",
    works: [
      [["A. A."], "Ars Amatoria."],
      [["Am."], "Amores."],
      [["Cons."], "Consolatio."],
      [["Fast.", "F."], "Fasti."],
      [["Hal."], "Halieuticon."],
      [["H."], "Heroides."],
      [["Ib."], "Ibis."],
      [["Med."], "Medicamina."],
      [["M."], "Metamorphoses."],
      [["Nux"], "Nux Elegia."],
      [["Pont."], "Epistolae ex Ponto."],
      [["R. Am."], "Remedia Amoris."],
      [["Tr."], "Tristia."],
    ],
  },
  {
    abbreviations: ["Pac. or Pacuv."],
    expansions: "M. Pacuvius, writer of Tragedy,",
    date: "fl. B.C. 154",
  },
  {
    abbreviations: ["Pacat."],
    expansions: "Latinus Pacatus Drepanius, panegyrist,",
    date: "fl. A.D. 391",
  },
  {
    abbreviations: ["Pall."],
    expansions: "Palladius Rutilius Taurus, writer on husbandry,",
    date: "perh. about fl. A.D. 350",
  },
  {
    abbreviations: ["Papin."],
    expansions: "Aemilius Papinius, lawyer,",
    date: "fl. A.D. 200",
  },
  {
    abbreviations: ["Paul."],
    expansions: "Julius Paullus, lawyer,",
    date: "fl. A.D. 210",
  },
  {
    abbreviations: ["Paul. Nol."],
    expansions: "Pontius Paulinus Nolanus, Chr. writer,",
    date: "ob. A.D. 431",
  },
  {
    abbreviations: ["Paul. Vict."],
    expansions: "Paulus Victor, topographer,",
    date: "fl. A.D. 390",
  },
  {
    abbreviations: ["Pers."],
    expansions: "A. Persius Flaccus, satirist,",
    date: "ob. A.D. 62",
  },
  {
    abbreviations: ["Petr."],
    expansions: "T. Petronius Arbiter, satirist,",
    date: "ob. A.D. 66",
  },
  {
    abbreviations: ["Phaedr."],
    expansions: "Phaedrus, fabulist,",
    date: "fl. A.D. 15",
  },
  {
    abbreviations: ["Plaut. or Pl."],
    expansions: "T. Maccius Plautus, writer of comedy,",
    date: "ob. B.C. 184",
    works: [
      [["Amph.", "Am."], "Amphitruo."],
      [["Asin.", "As."], "Asinaria."],
      [["Aul."], "Aulularia."],
      [["Bacch. or Bac."], "Bacchides."],
      [["Capt."], "Capteivei."],
      [["Cas."], "Casina."],
      [["Cist."], "Cistellaria."],
      [["Curc."], "Curculio."],
      [["Epid."], "Epidicus."],
      [["Men."], "Menaechmei."],
      [["Merc."], "Mercator."],
      [["Mil."], "Miles Gloriosus."],
      [["Most."], "Mostellaria."],
      [["Pers."], "Persa."],
      [["Poen."], "Poenulus."],
      [["Ps."], "Pseudolus."],
      [["Rud."], "Rudens."],
      [["Stich."], "Stichus."],
      [["Trin."], "Trinumus."],
      [["Truc."], "Truculentus"],
    ],
  },
  {
    abbreviations: ["Plin."],
    expansions: "C. Plinius Secundus (major),",
    date: "ob. A.D. 79",
    works: [[["H. N."], "Naturalis Historia. (Ed. Ian.; Teubner.)"]],
  },
  {
    abbreviations: ["Plin."],
    expansions: "C. Plinius Caecilius Secundus (minor),",
    date: "fl. A.D. 100",
    works: [
      [["Ep."], "Epistolae. (Ed. Gierig)"],
      [["Pan."], "Panegyricus."],
    ],
  },
  {
    abbreviations: ["Plin. Val."],
    expansions:
      "Plinius Valerianus, physician 3rd century; or, acc. to others,",
    date: "fl. A.D. 500",
  },
  {
    abbreviations: ["Pompon."],
    expansions: "Sextus Pomponius, lawyer,",
    date: "fl. A.D. 138",
  },
  {
    abbreviations: ["Porc. Latro."],
    expansions: "M. Porcius Latro, rhetorician,",
    date: "fl. B.C. 17",
  },
  {
    abbreviations: ["Prisc."],
    expansions: "Priscianus, grammarian, (Ed. Keil.).",
    date: "fl. A.D. 440",
  },
  {
    abbreviations: ["Prob."],
    expansions: "M. Valerius Probus, grammarian (date uncertain).",
  },
  {
    abbreviations: ["Prop."],
    expansions: "Sex. Aurelius Propertius, poet,",
    date: "fl. B.C. 30",
  },
  {
    abbreviations: ["Prud."],
    expansions: "Aurel. Prudentius Clemens, Chr. poet,",
    date: "fl. A.D. 397",
  },
  {
    abbreviations: ["Ps.-Quint."],
    expansions: "Pseudo-Quintilianus; the author (or authors) unknown.",
    works: [[["Decl."], "Declamationes."]],
  },
  {
    abbreviations: ["Ps. Apul."],
    expansions: "Pseudo Apuleius",
    works: [[["Dogm. Plat."], "De Dogmate Platonis"]],
  },
  {
    abbreviations: ["Publ. Syr."],
    expansions: "Publius Syrus, mimographer,",
    date: "fl. B.C. 44",
  },
  {
    abbreviations: ["Q. Cic."],
    expansions: "Quintus Cicero, brother of Tullius,",
    date: "ob. B.C. 43",
    works: [[["Pet. Consul."], "De Petitione Consulatus."]],
  },
  {
    abbreviations: ["Quint."],
    expansions: "M. T. Quintilianus, rhetorician,",
    date: "ob. A.D. 118",
  },
  {
    abbreviations: ["Ruf."],
    expansions: "Sextus Rufus, hist.",
    date: "fl. A.D. 364",
  },
  {
    abbreviations: ["Rutil."],
    expansions: "Claudius Rutilius Numatianus, poet,",
    date: "fl. A.D. 410",
  },
  {
    abbreviations: ["Sall."],
    expansions: "C. Sallustius Crispus, hist.",
    date: "ob. B.C. 34",
    works: [
      [["C.", "Cat."], "Catilina."],
      [["Hist."], "Historia. (Frag.)"],
      [["J."], "Jugurtha."],
    ],
  },
  {
    abbreviations: ["Salv."],
    expansions: "Salvianus, Chr. writer,",
    date: "fl. A.D. 475",
  },
  {
    abbreviations: ["Scaev."],
    expansions: "Q. Mucius Scaevola, lawyer,",
    date: "ob. B.C. 82",
  },
  {
    abbreviations: ["Scrib."],
    expansions: "Scribonius Largus, physician,",
    date: "fl. A.D. 43",
  },
  {
    abbreviations: ["Scrr. Eccl."],
    expansions: "Scriptores Ecclesiastici.",
    works: [
      [["Gram."], '"       Grammatici. (Ed. Putch and Lindemann.)'],
      [["Gromat."], '"       Gromatici. (Ed. Goes.)'],
      [["R. R."], '"       rei rusticae (Ed. Bipont.)'],
    ],
  },
  {
    abbreviations: ["Sedul."],
    expansions: "Coelius Sedulius, Chr. poet,",
    date: "fl. A.D. 450",
  },
  {
    abbreviations: ["Sen."],
    expansions: "M. Annaeus Seneca, rhetorician,",
    date: "fl. A.D. 15",
    works: [
      [["Contr."], "Controversiae."],
      [["Suas."], "Suasoriae."],
    ],
  },
  {
    abbreviations: ["Sen."],
    expansions: "L. Annaeus Seneca, philosopher,",
    date: "ob. A.D. 65",
    works: [
      [["Ben."], "De Beneticiis."],
      [["Brev. Vit."], "De Brevitate Vitae."],
      [["Clem."], "de Clementia."],
      [["Cons. ad Helv."], "Consolatio ad Helviam."],
      [["Cons. ad Marc."], "Consolatio ad Marciam."],
      [["Cons. ad Poly."], "Consolatio ad Polybium."],
      [["Const."], "De Constantia Sapientis."],
      [["Ep."], "Epistolae."],
      [["Ira", "Ir."], "de Ira."],
      [["Mort. Claud."], "De Morte Claudii Caes."],
      [["N. Q."], "Naturales Questiones."],
      [["Ot. Sap."], "De Otio Sapientis."],
      [["Prov."], "De Providentia."],
      [["Tranq."], "De Tranquillitate Anim."],
      [["Vit. Beat."], "De Vita Beata."],
    ],
  },
  {
    abbreviations: ["Sen."],
    expansions:
      "L. Annaeus Seneca, writer of tragedy (acc. to some, identical with the philosopher).",
    works: [
      [["Agam."], "Agamemnon."],
      [["Herc. Fur."], "Hercules Furens."],
      [["Herc. Oet."], "Hercules Oetaeus."],
      [["Hippol."], "Hippolytus."],
      [["Med."], "Medea."],
      [["Octav."], "Octavia."],
      [["Oedip."], "Oedipus."],
      [["Phoen."], "Phoenissae (or Thebais)"],
      [["Thyest."], "Thyestes."],
      [["Troad."], "Troades."],
    ],
  },
  {
    abbreviations: ["Ser. Samm."],
    expansions: "Q. Serenus Sammonicus, physician,",
    date: "ob. A.D. 212",
  },
  {
    abbreviations: ["Serv."],
    expansions: "Servius Maurus Honoratus, grammarian,",
    date: "fl. A.D. 395",
  },
  {
    abbreviations: ["Sev."],
    expansions: "Cornelius Severus, poet,",
    date: "fl. A.D. 10",
  },
  {
    abbreviations: ["Sic. Fl."],
    expansions: "Siculus Flaccus, writer on surveying,",
    date: "fl. A.D. 100",
  },
  {
    abbreviations: ["Sid.", "Sidon."],
    expansions: "Sidonius Apollinaris, Christian writer,",
    date: "ob. A.D. 482",
  },
  {
    abbreviations: ["Sil."],
    expansions: "C. Silius Italicus, poet,",
    date: "ob. A.D. 100",
  },
  {
    abbreviations: ["Sisenn."],
    expansions: "L. Cornelius Sisenna, hist. and orator,",
    date: "fl. B.C. 78",
  },
  {
    abbreviations: ["Sol."],
    expansions: "C. Julius Solinus, gram.",
    date: "fl. A.D. 238",
  },
  {
    abbreviations: ["Spart."],
    expansions: "Aelius Spartianus, biographer,",
    date: "fl. A.D. 293",
  },
  {
    abbreviations: ["Stat."],
    expansions: "P. Papinius Statius, poet,",
    date: "fl. A.D. 87",
    works: [
      [["Ach."], "Achilleis."],
      [["Silv.", "S."], "Silvae."],
      [["Theb.", "Th."], "Thebais."],
    ],
  },
  {
    abbreviations: ["Suet."],
    expansions: "C. Suetonius Tranquillus, biographer,",
    date: "fl. A.D. 116",
    works: [[["Caes."], "De Vitis Caesarum"]],
  },
  {
    abbreviations: ["Sulp."],
    expansions: "Sulpicius Severus, Christian writer,",
    date: "fl. A.D. 400",
  },
  {
    abbreviations: ["Symm."],
    expansions: "Q. Aurelius Symmachus, orator, etc.",
    date: "fl. A.D. 395",
  },
  {
    abbreviations: ["Tac."],
    expansions: "C. Cornelius Tacitus, hist.",
    date: "perh. ob. A.D. 118",
    works: [
      [["A."], "Annales."],
      [["Agr."], "Agricola."],
      [["G."], "Germania."],
      [["H."], "Historia."],
      [["Or."], "De Oratoribus."],
    ],
  },
  {
    abbreviations: ["Ter."],
    expansions: "P. Terentius Afer, writer of comedy,",
    date: "ob. B.C. 159",
    works: [
      [["Ad."], "Adelphi."],
      [["And."], "Andria."],
      [["Eun."], "Eunuchus."],
      [["Heaut."], "Heautontimorumenos."],
      [["Hec."], "Hecyra."],
      [["Ph."], "Phormio."],
    ],
  },
  {
    abbreviations: ["Ter. Maur."],
    expansions: "Terentianus Maurus, gram.",
    date: "fl. A.D. 100",
  },
  {
    abbreviations: ["Tert."],
    expansions: "Q. Septimius Florens Tertullianus, Chr. writer,",
    date: "fl. A.D. 195",
  },
  {
    abbreviations: ["Theod. Prisc."],
    expansions: "Theodorus Priscianus, physician,",
    date: "fl. A.D. 397",
  },
  {
    abbreviations: ["Tib."],
    expansions: "Albius Tibullus, poet,",
    date: "ob. B.C. 18",
  },
  {
    abbreviations: ["Titinn."],
    expansions: "Titinnius, writer of comedy,",
    date: "fl. B.C. 170",
  },
  {
    abbreviations: ["Treb. Poll."],
    expansions: "Trebellius Pollio, hist.",
    date: "fl. A.D. 320",
  },
  {
    abbreviations: ["Turp."],
    expansions: "Sextus Turpilius, writer of comedy,",
    date: "ob. B.C. 101",
  },
  {
    abbreviations: ["Ulp."],
    expansions: "Domitius Ulpianus, lawyer,",
    date: "ob. A.D. 228",
  },
  {
    abbreviations: ["Val. Cato."],
    expansions: "Valerius Cato, poet,",
    date: "about fl. B.C. 80",
  },
  {
    abbreviations: ["Val. Fl."],
    expansions: "C. Valerius Flaccus, poet,",
    date: "fl. A.D. 70",
  },
  {
    abbreviations: ["Val. Max."],
    expansions: "Valerius Maximus, hist.",
    date: "fl. A.D. 26",
  },
  {
    abbreviations: ["Varr."],
    expansions: "M. Terentius Varro, writer on husbandry, etc.",
    date: "ob. B.C. 28",
    works: [
      [["L. L."], "De Lingua Latina. (Ed. Müller 1833)."],
      [["R. R."], "De Re Rustica."],
    ],
  },
  {
    abbreviations: ["Veg."],
    expansions: "F. Renatus Vegetius, writer De Re Militari,",
    date: "fl. A.D. 386",
  },
  {
    abbreviations: ["Veg."],
    expansions: "P. Vegetius Renatus, writer De Re Veterinaria",
    date: "(his date is uncertain, but was long subsequent to that of the preceding author).",
  },
  {
    abbreviations: ["Vell."],
    expansions: "C. Velleius Paterculus, hist.",
    date: "fl. A.D. 30",
  },
  {
    abbreviations: ["Venant."],
    expansions: "Venantius Fortunatus, Chr. poet,",
    date: "fl. A.D. 600",
  },
  {
    abbreviations: ["Ver. Flac."],
    expansions: "Verrius Flaccus, gram.",
    date: "fl. B.C. 20",
  },
  {
    abbreviations: ["Virg."],
    expansions: "P. Virgilius Maro, poet,",
    date: "ob. B.C. 19",
    works: [
      [["Aen."], "Aeneis."],
      [["Cat."], "Catalecta."],
      [["Cir."], "Ciris."],
      [["Cop."], "Copa."],
      [["E."], "Eclogae."],
      [["G."], "Georgica."],
      [["Mor.", "M."], "Moretum."],
    ],
  },
  {
    abbreviations: ["Vitr."],
    expansions: "Vitruvius Pollio, writer on architecture, (Ed. Schneider.).",
    date: "fl. B.C. 20",
  },
  {
    abbreviations: ["Vop."],
    expansions: "Flavius Vopiscus, hist.",
    date: "fl. A.D. 306",
  },
  {
    abbreviations: ["Vulc. Gall."],
    expansions: "Vulcatius Gallicanus, historian,",
    date: "about fl. A.D. 292",
  },
  {
    abbreviations: ["Vulg."],
    expansions: "Biblia Vulgatae Editionis.",
  },
];
