export const SH_SKIPS = new Set<string>([
  "FISSURE",
  "VIATOR",
  "TO THRESH OUT",
  "lit.",
  "IMBEDDED",
  "TO STUPIFY",
  "STUPIFY",
  "STUPIFIED",
  "IMMOVABLE",
  "CONTEMPORANEOUS",
  "viz.",
  "VOX",
  "q. v.",
  "judices",
  "TO B. ABOUT",
  "C.-BALL",
  "CREED",
  "SATISFIED",
  "DALE",
  "RELIABLE",
  "SPRUNG",
  "TRUNCATED",
  "TO CON-*",
  "UNPOLITE",
  "DISQUALIFIED",
  "TO (LET) GO",
  "(GET) RID OF",
  "UNSEAT",
  "*MENT",
  "UNREAL",
  "*PEN",
  "GREASINESS",
  "SATISFIED",
  "SUBTILTY",
  "SUBTILTY",
  "(BE ON) FIRE",
  "F.-FOLD",
  "(TO MAKE) FREE WITH",
  "(regard)",
  "(so called)",
  "SUBTILTY",
  "(of pirates)",
  "-FOLD",
  "IRREPRESSIBLE",
  "S PARATE",
  "IRREPRESSIBLE",
  "(IT) MATTERS",
  "*THROW",
  "scheda",
  "*SNARE",
  "DÉPOT",
  "MULTI-*LATERAL",
  "MENSES",
  "(of elephants)",
  "cliens",
  "philosophia is",
  "COMMISERATION",
  "*BODE",
  "P. IN",
  "&c.",
  "sc.",
  "DISQUALIFIED",
  "LITIGIOSUS",
  "usu.",
  "id.",
  "(IN) HASTE",
  "Q.-SIGHTEDNESS",
  "(AT) REST",
  "(AT) REST",
  "TO SUB-*",
  "PACIFIER",
  "COM-*",
  "*TIONALLY",
  "(BY) CHANCE",
  "usu.",
  "SUBJUGATION",
  "DELI-*",
  "RE-CREATE",
  "RE-*UNITE",
  "TO RECOMPENSATE",
  "(FLEE FOR) REFUGE",
  "SHAKY",
  "STUPIFIED, TO BE",
  "RAID",
  "PLETHORIC",
  "SEQUESTERED",
  "usu.",
  "CHOSEN",
  "CO-HEIR",
  "PRETENTIOUS",
  "TERRIFIED",
  "SYLVAN",
  "DETRACTER",
  "SATIRIZE",
  "PRETENTIOUS",
  "PRETENTIOUS",
  "-DRIFT",
  "*TUNE",
  "*SORROW",
  "RELIABLE",
  "MIS-STATEMENT",
  "S.-HOUSE",
  "STAUNCH",
  "[IN] TURN",
  "(BE AT THE) HEAD OF",
  "*PORT",
  "TRICLINIUM",
  "TRIFORM",
  "(WITH) REGARD (TO)",
  "VES-*",
  "(FALSE) ACCUSER",
  "librarii",
  "TRANS-*",
  "UNACQUITTED",
  "UNSUPPORTED",
  "CEILED",
  "UNVARYING",
  "UNPLUNDERED",
  "DEVELOPMENT",
  "PRETENTIOUS",
  "UNTRAMMELLED",
  "UNAUTHORIZED",
  "UNPROSPEROUS",
  "[IN] VAIN",
  "UNFLAGGING",
  "UNMEN-*",
  "UNPROMPTED",
  "(AGAINST ONE'S) WILL",
  "[ON THE] TOP",
  "(OF NO) AVAIL",
  "[TO BE OF] USE",
  "judex",
  "SATISFIED, TO BE",
  "*TROL",
  "P. ON",
  "RA-*",
  "(TO KEEP) SILENCE",
  "*DUE",
  "*POSEDLY",
  "*BERATION",
  "RE-*MOULD",
  "*TIGE",
  "*FORM",
  "*TIONED",
  "P. UPON",
  "*PIDLY",
  "FACIO",
  "(IN) HASTE.",
]);

export const LINK_EDGE_CASES = new Map<string, string>([
  ["TO SIDE WITH", "side"],
  ["FIAT", "so"],
  ["BE IT SO", "so"],
  ["LICENCE", "license"],
  ["IRASCIBLE", "irascibility"],
  ["WORN OUT", "wear"],
  ["WORN", "wear"],
  ["CORSLET", "corselet"],
  ["IMMOVABLE", "immoveable"],
  ["WORN (OUT)", "wear"],
  ["BLAMABLE", "blameable"],
  ["BLAMABLY", "blameably"],
  ["TESSELATED", "tessellated"],
  ["STEDFASTNESS", "steadfastness"],
  ["STEDFAST", "steadfast"],
  ["PRONUNTIATION", "pronunciation"],
  ["DYING", "die"],
  ["CANNOT", "can"],
]);
