[package]
name = "morceus"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json.workspace = true

[[bin]]
name = "cli"
path = "src/main.rs"

[lib]
crate-type = ["rlib"]
path = "src/lib.rs"
