on:
  workflow_call:

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    env:
      LATEST: ghcr.io/nkprasad12/morcus:dev-latest
      PREVIOUS: ghcr.io/nkprasad12/morcus:dev-previous
      CANDIDATE: ghcr.io/nkprasad12/morcus:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build . --tag $CANDIDATE --label "runnumber=${GITHUB_RUN_ID}"
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Backup current image
        run: docker pull $LATEST && docker tag $LATEST $PREVIOUS && docker push $PREVIOUS || true
      - name: Push dev image
        run: |
          docker push $CANDIDATE
          docker tag $CANDIDATE $LATEST
          docker push $LATEST
