name: fast-forward
on:
  issue_comment:
    types: [created]
jobs:
  fast-forward:
    if: ${{ contains(github.event.comment.body, '/fast-forward')
      && github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write

    steps:
      - name: Fast forwarding
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          comment: always

  promote-image:
    runs-on: ubuntu-latest
    needs: [fast-forward]
    timeout-minutes: 3

    steps:
      - uses: actions/checkout@v4
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Fetch dev image
        run: timeout 2m bash -c 'until docker pull ghcr.io/nkprasad12/morcus:${{ github.sha }}; do sleep 10; done'
      - name: Backup current image
        run: |
          LATEST=ghcr.io/nkprasad12/morcus:main-latest
          PREVIOUS=ghcr.io/nkprasad12/morcus:main-previous
          docker pull $LATEST && docker tag $LATEST $PREVIOUS && docker push $PREVIOUS || true
      - name: Promote dev image
        run: |
          LATEST=ghcr.io/nkprasad12/morcus:main-latest
          CANDIDATE=ghcr.io/nkprasad12/morcus:${{ github.sha }}
          docker tag $CANDIDATE $LATEST
          docker push $LATEST
